version: '3'

services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    env_file:
      - .env.production
    environment:
      - "VIRTUAL_HOST=DOMAIN"  # for jwilder/nginx-proxy
      - "LETSENCRYPT_HOST=DOMAIN"  # for jrcs/letsencrypt-nginx-proxy-companion
    expose:
      - 80  # for jwilder/nginx-proxy
    networks:
      - nginx-proxy
      - app
    volumes:
      - uploads:/docroot/uploads
    restart: always
    depends_on:
      - app

  app:
    build:
      context: .
      dockerfile: Dockerfile.production
    env_file:
      - .env.production
      - .env.production.secret
    networks:
      - app
    volumes:
      - uploads:/app/public/uploads
    restart: always
    depends_on:
      - db

  db:
    image: postgres:12-alpine
    env_file:
      - .env.production
    networks:
      - app
    volumes:
      - db:/var/lib/postgresql/data
      - ./docker/init-pg.sh:/docker-entrypoint-initdb.d/init-pg.sh
    restart: always

networks:
  nginx-proxy:
    external: true
  app:

volumes:
  uploads:
  db:
