version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.development
    networks:
      - app
    ports:
      - 127.0.0.1:${APP_PORT-3000}:3000
    volumes:
      - .:/app

networks:
  app:
