default: &default
  adapter: postgresql
  host: '<%= ENV["PG_HOST"] %>'
  username: '<%= ENV["PG_USER"] %>'
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: '<%= ENV["PG_DB"] || "APP_NAME_development" %>'

test:
  <<: *default
  database: '<%= ENV["PG_DB"] || "APP_NAME_test" %>'

production:
  <<: *default
  database: '<%= ENV["PG_DB"] || "APP_NAME_production" %>'
