default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: ra1_development

test:
  <<: *default
  database: ra1_test

production:
  <<: *default
  database: ra1_production
  username: ra1
  password: <%= ENV['RA1_DATABASE_PASSWORD'] %>
